name: Gerar APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar EAS CLI Globalmente
        run: npm install -g eas-cli

      - name: Limpar Cache do NPM
        run: npm cache clean --force

      - name: Instalar Dependencias do Projeto
        run: npm install --no-package-lock --legacy-peer-deps

      - name: Construir o APK no EAS
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_TMDB_API_KEY: ${{ secrets.EXPO_PUBLIC_TMDB_API_KEY }}